### PR TITLE
Fix line endings and update to Faucet HTTP v1.1.1

### PR DESCRIPTION
**Pull request by TazeTSchnitzel**
[Faucet HTTP v1.1.1](https://github.com/TazeTSchnitzel/Faucet-HTTP-Extension/releases/tag/V1.1.1) fixes the second half of https://github.com/Gang-Garrison-2/Gang-Garrison-2/issues/157 and warns about the first half.

The line endings were screwed up because of Game Maker, surprisingly. Faucet HTTP's script group file is entirely CRLF, but when Game Maker imports it, it converts it to LF (I know, right?). So after importing, you have to save gg2.gmk, do `./gmktogit`, `unix2dos gg2/Scripts/Faucet\ HTTP/*`, `./gittogmk`... ugh.

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
Oh, this accidentally changes `gg2/Game Information.txt`. Will revert.

**Comment by TazeTSchnitzel** [comment]
Fixed.

**Comment by TazeTSchnitzel** [comment]
Oh dear, this will always do a GET redirect even if the original request was POST. Not a problem for our use-case, but not standards-compliant. I'll fix that sometime.

**Comment by Medo42** [comment]
How does this actually fix the bug, except for the added comment?

**Pull request merged**
