### PR TITLE
catch alt f4

### PR DESCRIPTION
**Pull request by arctic5**
It's pretty common for bad trolls to try and answer every newbie question with
alt f4 in an attempt to close their game so I believe something needs to be
put in place to counter it

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
Does this actually work? (I assume so.)

Maybe the commit could be better named, perhaps `Do not close when Alt+F4 pressed`.

Anyway, this might be a good idea. I don't think anyone would be inconvenienced.

**Comment by Medo42** [comment]
No. I really prefer Alt-F4 to work as expected. There is no real harm in people closing the game, and they'll only do it once or twice before realizing what Alt-F4 does.

**Comment by TazeTSchnitzel** [comment]
Fair enough, you're right. If a newbie does it, they will quickly figure it out, and nothing's really lost. GG2 only takes a few seconds to restart.

**Comment by arctic5** [comment]
well darn

**Pull request closed without merging**
