### PR TITLE
Updated 7za version and license

### PR DESCRIPTION
**Pull request by PrOF-kk**
Fixes https://github.com/Gang-Garrison-2/Gang-Garrison-2/issues/207
The license change was only for copyright year and minor details, as 7za now is in the "7-zip Extra" bundle
Tested

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
Just to make sure: this is the 32-bit, not 64-bit, version right?

**Comment by PrOF-kk** [comment]
Yes... actually somehow git didn't push the actual exe with its meta file. Fixed now, sorry for the inconvenience

**Comment by Medo42** [comment]
Please update again to 18.01 :sweat_smile:

**Comment by PrOF-kk** [comment]
Alright. Now just cherrypick https://github.com/Medo42/Gang-Garrison-2/pull/308/commits/ded41c223eb9ab456b067cfadc0e462a9223a62d and https://github.com/Medo42/Gang-Garrison-2/pull/308/commits/aac37c0f87466e4cc6d955d95d810d9f2c4d7c19 so the project's history isn't clogged with mistakes or useless commits. Thanks :+1:
I hope I did this right this time

**Comment by Medo42** [comment]
Tested the updater and it still works :)

**Pull request merged**
