### PR TITLE
Allow toggling scoreboard fading (hidden ini setting)

### PR DESCRIPTION
**Pull request by TazeTSchnitzel**
This would "fix" https://github.com/Gang-Garrison-2/Gang-Garrison-2/issues/131 in a way.

### CODE REVIEW

**Comment by Medo42** [comment]
I'm definitely against adding an option for it, and I don't really see a problem with the fading as it is.

**Comment by TazeTSchnitzel** [comment]
It takes too long to fade out (especially on wine), preventing you from seeing the game

**Comment by Medo42** [comment]
Well, let's just make it "not now" then :)

**Comment by arctic5** [comment]
"make a delta factor plugin"

**Comment by wareya** [comment]
But why?

**Comment by TazeTSchnitzel** [comment]
I closed it because it was unlikely to succeed

**Comment by wareya** [comment]
?_? what a stupid reason

**Comment by arctic5** [comment]
i thought this idea was stupider than the reason

**Comment by TazeTSchnitzel** [comment]
It's not stupid, it provides a real benefit.

**Comment by arctic5** [comment]
making the scoreboard look bad is not a benefit, fixing lag bcs you are playing gg2 on a weak as heck linux machine that cant even get 30 fps is a personal problem that you can solve on your own instead of forcing it upon people who are reasonable enough to play gg2 on windows

**Comment by wareya** [comment]
just tie it to the particles setting, that's what it's for

**Comment by arctic5** [comment]
i play with my particles off screw off

**Comment by wareya** [comment]
where else would you put it arctic-kouhai????

**Comment by arctic5** [comment]
u dont put it, theres no reason to add it anyways

**Comment by wareya** [comment]
even between me and AJF who are like completely different we both want this. i think it looks like crap and it makes it impossible for him to play. there is no way that there are not more people like us out there and there is zero problem from adding this in if it's tied to an option.

**Comment by TazeTSchnitzel** [comment]
Also, the graphical effect is fairly gratuitous and a distraction. Valve's own games don't have this fading, and that means the moment you lift your finger, the screen is *gone* and you can focus on the game again, while GG2 makes you wait for it to slowly fade out.

Also, *she. :p

**Comment by wareya** [comment]
"he" is my gender-neutral pronoun since my gender identity is "human"

**Comment by TazeTSchnitzel** [comment]
...wat

**Comment by wareya** [comment]
8)

**Comment by TazeTSchnitzel** [comment]
OK, now it's a hidden INI setting to allow you to turn of scoreboard fading (no point in a GUI).

Can has merge pl0x? Did test, does work (scoreboard fading works as before, turning it off works, yay).

**Comment by arctic5** [comment]
hidden options are lazy as heck

**Comment by wareya** [comment]
If performance is a problem then hidden options > no option at all

AND GUESS WHAT THIS IS ABOUT TO AJF

**Comment by arctic5** [comment]
howabout you make use of the tabs that are there for a reason???

**Comment by TazeTSchnitzel** [comment]
what

**Comment by wareya** [comment]
http://i.imgur.com/wru2JV2.png

**Pull request merged**
