### PR TITLE
Implemented [", " delimiter instead of just ","] and fixed an issue

### PR DESCRIPTION
**Pull request by PrOF-kk**
http://www.ganggarrison.com/forums/index.php?topic=33909.0
Really simple change, tested successfully, doesn't break UUID compatibility

### CODE REVIEW

**Comment by Medo42** [comment]
Careful, this pull request is for your master branch, so all your new commits ended up here as well now.

Also, I've pushed b90672a8f8ba34d5d6e858da2dd2a279ad7509db now which implements this in a slightly nicer way - didn't want spaces in plugin names to be lost. Yes I know there are no plugins with spaces. Shuddup.

**Comment by PrOF-kk** [comment]
Yeah, I should've requested from another branch. Anyway the other 2 commits are still valid and ready to be merged, if you want 👍 
Nice job on the trim script, way nicer than my solution

**Comment by Medo42** [comment]
Already cherrypicked and pushed :)

**Comment by PrOF-kk** [comment]
👍

**Pull request closed without merging**
