### PR TITLE
Fix loose sheet animations not being adapted to fps settings (fixes #156)

### PR DESCRIPTION
**Pull request by Medo42**
Doing this via github because I'm in Canada right now and not set up for gg2 dev over here. That also means I can't test, so that should be done before merging.
This fixes Gang-Garrison-2/Gang-Garrison-2#156.

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
Hey, why do we even have to manually adjust image speeds anyway? Would @wareya care to comment on why the RateController thing doesn't step the animation forward slower/faster for you?

**Comment by wareya** [comment]
with(all) HAHAHANO.

**Comment by TazeTSchnitzel** [comment]
ah

**Comment by Medo42** [comment]
This should be it.

**Comment by Medo42** [comment]
Oh well, not working quite as planned but it will probably find the reference once we merge.

**Comment by TazeTSchnitzel** [comment]
It won't. For comments, it only recognises the format `(fixes #xxx)`, where `#xxx` is some issue in the same repo.

What you *can* do is put a link in the OP of this pull request preceded by "fixes ".

**Pull request merged**
