### PR TITLE
GGON improvements

### PR DESCRIPTION
**Pull request by aeyrow**

### CODE REVIEW

**Comment by arctic5** [comment]
i think it would too and i took a stab at doing it, then i decided i hate string parsing

**Comment by arctic5** [comment]
hi ajf

**Comment by TazeTSchnitzel** [comment]
Hi arctic, happy 2015!

**Comment by TazeTSchnitzel** [comment]
Whoever merges this, mark it as fixing https://github.com/Gang-Garrison-2/Gang-Garrison-2/issues/137. I suggest rebase + squash, then amend the commit message.

**Pull request merged**
