### PR TITLE
use a switch case

### PR DESCRIPTION
**Pull request by TazeTSchnitzel**
Since arctic tried to thwart my previous attempt at revival: https://github.com/Medo42/Gang-Garrison-2/pull/253

A revival of https://github.com/Medo42/Gang-Garrison-2/pull/250

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
Commit was recreated like so:

    $ wget https://github.com/arctic5/Gang-Garrison-2/commit/916f0d6ae79ec36708c75b43da315706d4eb8126.patch
    $ git checkout cbe17f7a7c51612dd73b6e05c17dc7f43ee64494
    $ git checkout -b ggon-stuff
    $ git apply 916f0d6ae79ec36708c75b43da315706d4eb8126.patch
    $ GIT_COMMITTER_NAME="arctic" GIT_COMMITTER_EMAIL="icyfreeze5@gmail.com" GIT_COMMITTER_DATE="Thu, 15 Jan 2015 01:08:15 -0800" GIT_AUTHOR_DATE="Thu, 15 Jan 2015 01:08:15 -0800" git commit --author="arctic <icyfreeze5@gmail.com>" -m 'use a switch case'

**Comment by TazeTSchnitzel** [comment]
Now to see if it's faster.

**Comment by TazeTSchnitzel** [comment]
Benchmarking plugin:

```Game Maker Language
var largeMap;
largeMap = '{';

var i;
for (i = 0; i < 1000; i += 1)
{
    if (i > 0)
        largeMap += ',';
    largeMap += string(i) + ': ' + string(i);
}

largeMap += '}';

var runs;
for (runs = 0; runs < 10; runs += 1)
{
    var startTime, endTime, map;

    startTime = current_time;
    map = ggon_decode(largeMap);
    endTime = current_time;

    results[runs] = endTime - startTime;
    ds_map_destroy(map);
}

var i, resultsString;
resultsString = 'Times for each run: ';
for (i = 0; i < runs; i += 1)
    resultsString += string(results[i]) + 'ms ';
resultsString += '#Average time for all ' + string(runs) + ' runs: ';
var i, total;
total = 0;
for (i = 0; i < runs; i += 1)
    total += results[i];
resultsString += string(total/runs) + 'ms';

show_message(resultsString);
```

**Comment by TazeTSchnitzel** [comment]
output for master:

    Times for each run: 77ms 78ms 77ms 79ms 68ms 91ms 91ms 73s 77s 70ms
    Average time for all 10 runs: 78.10ms

output for master with this merged:

    Times for each run: 69ms 70ms 58ms 77ms 68ms 64ms 64ms 73ms 66ms 61ms
    Average time for all 10 runs: 67ms

Looks like this actually is a slight improvement!

**Comment by Medo42** [comment]
To say it in the words of Mr. Freeze: "Who would have thawed?"

**Pull request merged**
