### PR TITLE
Readd "surfing"

### PR DESCRIPTION
**Pull request by arctic5**
Because of popular demand (to the extent possible with the current community) I think we should revert this commit. It should be ok because its not really a new feature right?

### CODE REVIEW

**Comment by Medo42** [comment]
Oh boy, spinjumping 2.0
Care to link to the popular demand on the forum?

**Comment by arctic5** [comment]
It's not really on the forum but more of steam and skype where the majority of the remaining gg2 community resides but if you insist here's one

http://www.ganggarrison.com/forums/index.php?topic=35413.msg1255742#msg1255742

**Comment by TazeTSchnitzel** [comment]
So what you're saying is a few of your friends want it.

**Comment by arctic5** [comment]
if a few of my friends, aka probably not your friends means a majority of the active gg2 community, then yes

**Comment by TazeTSchnitzel** [comment]
Look, I don't think a few of your Steam friends really counts as "the GG2 community". Make a proper forum thread in feature requests.

**Comment by arctic5** [comment]
>TazeTSchnitzel commented 13 hours ago
Look, I don't think a few of your Steam friends really counts as "the GG2 community". Make a proper forum thread in feature requests.

image
Look, I think you are utterly retarded if you think that 2 or so steam friends counts as a gg2 community especially if you don't even take part in it and are making stupid assumptions about. Make a proper *well informed* argument and dont tell me what to do

**Comment by TazeTSchnitzel** [comment]
> Look, I think you are utterly retarded if you think that 2 or so steam friends counts as a gg2 community

Why are you arguing against yourself? Isn't this what I accused *you* of?

Also, let's be civil and not use mental health slurs, please.

> especially if you don't even take part in it

I'm far from as active in GG2 as I once was, but I'm not *entirely* inactive. And this is besides the point, anyhow. *Tu quoque* is not an argument, it is a fallacy.

> Make a proper well informed argument and dont tell me what to do

How is my "argument" "poorly-informed"? I am saying that your unsubstantiated claims for support for this change are not sufficient. I am saying that, if you wish to make a gameplay change like this, you should create a forum thread. I think there is a risk of selection bias and such in just mentioning that some people disliked surfing's removal - that doesn't mean most people want it back, necessarily.

Rather than getting uncivil and arguing about it, why not make an actual forum thread? Are you scared people might disagree with the change?

**Comment by TazeTSchnitzel** [comment]
Anyway, I made a thread myself since I think it's not unreasonable to ask about it. Who knows, maybe everyone hates it.

http://www.ganggarrison.com/forums/index.php?topic=36412.0

**Comment by arctic5** [comment]
you're the one that thinks a or 2 people was a gg2 community, i never stated that in any way

**Comment by TazeTSchnitzel** [comment]
I never said that either, I don't know what you're getting at.

I said that a few *of your friends* does *not* constitute the GG2 community.

**Comment by Medo42** [comment]
It looks like there is sufficient demand to re-add surfing in some way. It's a difficult call how to do this properly though. One option is to make it an entity property which defaults to the "proper" behavior, but then we break existing surfing maps (how many of those are around of those?)
We could also make it default to the surfing behavior if no entity property is set, and let Garrison Builder set the non-surfing property by default. This would keep old maps which don't want surfing broken, but new maps and old surfing maps would be ok. Or we could just use this PR, which means that old and new 'normal' uses of the dropdown platform are glitchy, but surfing maps still work and the behavior of dropdown platforms is uniform (no surprises)

I lean towards the first option, leaving the dropdown platforms fixed but making it possible to re-add surfing behavior to the affected maps if anyone cares enough.

**Comment by arctic5** [comment]
o well i guess we arent having it

**Comment by arctic5** [comment]
I shall close this now and redo it later

**Comment by Medo42** [comment]
Close it once you have re-done it, I'd like to keep at least one thing open to remind of this issue.

**Comment by arctic5** [comment]
zzz

**Comment by arctic5** [comment]
https://github.com/Medo42/Gang-Garrison-2/pull/289

**Pull request closed without merging**
