### PR TITLE
check for chr10 and 13 in name change

### PR DESCRIPTION
**Pull request by arctic5**

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
Player names aren't the only place this would be useful. Perhaps make it a function? Then it could be used for server names and such too.

**Comment by TazeTSchnitzel** [comment]
Oh, also, does CR actually cause a line break in GML? I'd think only LF is a problem. Haven't tested tho.

**Comment by TazeTSchnitzel** [comment]
Though actually changing people's names if they have a `#` in them is a bad solution anyway. We already have a better one: escape `#` when displaying the name. We could do something similar for LF by replacing it with a space maybe.

**Comment by Medo42** [comment]
Please use descriptive commit coments. And before you ask: yes, I'm serious.

**Comment by arctic5** [comment]
y'know now that I think about it, having a vertical name on the scoreboard is a pretty nice gimmick to have

**Comment by TazeTSchnitzel** [comment]
you shouldn't be able to have it, it's obnoxious

**Comment by arctic5** [comment]
it's hilarious XD

**Pull request closed without merging**
