### PR TITLE
Fixes I owe some people

### PR DESCRIPTION
**Pull request by arctic5**
unnerf medic: Strychnine
broken flares: Sani
ok good night

tbh i really dont know/forgot how the medic nerf got mixed into the list of balance changes

### CODE REVIEW

**Comment by ZaSpai** [comment]
I honestly think a discussion on the medic heal rate is warranted on forum, but I'll admit that I feel the drop to 3/s is a little harsh. I think in the context of how the beta builds came about, and with the pyro 'buff' movement coming to the forefront (flare AOE burn, flame pen, HP adjustments, flame damage changes) and stuff, trying to alter medic's stats while pyro was getting tweaks that potentially would counter pre 2.8 medic probably was a result of poor communication somewhere down the line (I can't lay blame on anyone since I don't think it was the fault of any one person).

**Comment by arctic5** [comment]
no it isnt

**Comment by wareya** [comment]
Which medic nerf are we even talking about here? There are so many you have to be explicit if you want conversation.

The one that I pushed through was nothing if not entirely deliberate and even currently working as intended.

**Comment by wareya** [comment]
Okay, so we're talking about having nerfed regen for some reason. Regen was always a hard topic, and some people wanted to put a healing curve on it but Psycho blocked that.

5 was always a tad high; is 3 too low? You might want to try 4.

**Comment by arctic5** [comment]
someone wanted medic to have nerfed regen after taking damage recently if thats what you mean

**Comment by wareya** [comment]
yes that's what a healing curve is

**Comment by arctic5** [comment]
Well its been a long time since psycho was around and things have changed since then, so maybe?

**Pull request merged**
