### PR TITLE
use a switch case because its slightly faster

### PR DESCRIPTION
**Pull request by TazeTSchnitzel**
arctic closed this for some reason? https://github.com/Medo42/Gang-Garrison-2/pull/250

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
Needs benchmarks.

**Comment by arctic5** [comment]
doesn't mean you'll get any

**Comment by TazeTSchnitzel** [comment]
I'm going to do some.

**Comment by arctic5** [comment]
dont count on too much improvement since my computer is variably laggy

**Comment by arctic5** [comment]
HA! YOU THOUGHT THERE WAS SOMETHING HERE TO SEE DIDNT YOU?

**Comment by TazeTSchnitzel** [comment]
ok I'll merge it but attribute it to me instead

**Comment by TazeTSchnitzel** [comment]
You can't completely erase history, arctic. Before you fucked up the branch, it had this commit: https://github.com/arctic5/Gang-Garrison-2/commit/916f0d6ae79ec36708c75b43da315706d4eb8126

**Comment by arctic5** [comment]
cant fucking make the old pr keep up with the branch either..

**Comment by Medo42** [comment]
How does github manage repo cleanup anyway? Throw away nothing? Count
branches and tags as entry points and let links go dead? Or count internal
links as entry points, too? Apparently, it also keeps references in the
network alive if a repo is deleted which was technically the only one with
the commit in question, at least that's what happened with the bending heal
stream pull request.

Andrea Faulds <notifications@github.com> schrieb am Do., 02.04.2015, 14:13:

**Comment by TazeTSchnitzel** [comment]
Even though that commit stuck around, it's impossible to pull an unnamed (i.e. without branch or tag) commit from a remote repo. However, GitHub lets you get a patch. :)

**Comment by TazeTSchnitzel** [comment]
Oh wow. By getting the author, committer, author date, committer date, commit message, and commit content correct, I managed to recreate the original commit with an identical SHA-1 hash(!): https://github.com/Medo42/Gang-Garrison-2/pull/260

**Pull request closed without merging**
