### PR TITLE
use a switch case because its slightly faster

### PR DESCRIPTION
**Pull request by arctic5**
unit test benchmark
w/o modification
3291 ms

switch case thing
1435 ms

(i only ran 1 test for each so dont expect these to be too accurate)

edit: wtf is up with that diff

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
The diff is a mess because line endings.

**Comment by TazeTSchnitzel** [comment]
Also you should probably run the test multiple times so it's a more representative result

**Comment by Medo42** [comment]
Diff mess due to line endings? Just like your own PR you mean?

Andrea Faulds <notifications@github.com> schrieb am Do., 15.01.2015, 12:28:

**Comment by TazeTSchnitzel** [comment]
@Medo42 Yes, my PR (unintentionally) fixed the line endings to CRLF, I *think*. Lorgan committed LF, I *think*. That's probably sort of my fault because he had to import one of them multi-script .gml exports.

**Comment by arctic5** [comment]
yea ok iunno how to fix it

**Comment by TazeTSchnitzel** [comment]
Did you set up autocrlf?

**Comment by arctic5** [comment]
not sure but the 2 commits i tried were me pressing some notepad++ buttons and commiting the result

**Comment by TazeTSchnitzel** [comment]
Was the original commit produced by `gmksplit`?

**Comment by arctic5** [comment]
ye

**Comment by TazeTSchnitzel** [comment]
Had you done the `core.autocrlf` thing on your git repo ages ago?

**Comment by arctic5** [comment]
yes, thats why i dont get a million difs

**Comment by TazeTSchnitzel** [comment]
Hmm... lemme see if I can fix these files...

**Comment by TazeTSchnitzel** [comment]
Yep, my PR fixed some to CRLF. [This new PR over here](https://github.com/Medo42/Gang-Garrison-2/pull/251) would fix the rest.

Arctic has a huge diff because he's converted it *back* to LF for whatever reason?

**Comment by TazeTSchnitzel** [comment]
Yay looks like stuff's fixed

**Comment by Medo42** [comment]
Nice.

Unfortunately I don't trust benchmarks that were run exactly once, under unknown conditions. Can you add some more confidence to that by at least running the tests again, and then again in reverse order, to make sure the results are not distorted by caching?

**Comment by TazeTSchnitzel** [comment]
What MedO said.

**Comment by arctic5** [comment]
later

**Comment by arctic5** [comment]
ok w/e i close this there probably isnt a huge speed difference anyways

**Comment by Medo42** [comment]
Wtf?

jason <notifications@github.com> schrieb am Di., 03.02.2015, 13:41:

**Comment by TazeTSchnitzel** [comment]
huh?

**Comment by TazeTSchnitzel** [comment]
Why did you close it, @arctic5?!

**Comment by arctic5** [comment]
>there probably isnt a huge speed difference anyways

**Comment by TazeTSchnitzel** [comment]
but leaving it open requires no effort on your part

We will happily wait a decade for benchmarks if we must

**Comment by arctic5** [comment]
nah

**Comment by TazeTSchnitzel** [comment]
no, really

**Comment by arctic5** [comment]
lets stop discussing this

**Comment by TazeTSchnitzel** [comment]
No. You closed a pull request for no good reason.

**Comment by arctic5** [comment]
k

**Comment by TazeTSchnitzel** [comment]
Well if you won't reopen it, I will: https://github.com/Medo42/Gang-Garrison-2/pull/253

**Pull request closed without merging**
