### PR TITLE
use user configured controls for gb

### PR DESCRIPTION
**Pull request by arctic5**

### CODE REVIEW

**Comment by Medo42** [comment]
Are you sure this can never cause conflicts with existing controls in GB? I must confess I know next to nothing about it ;)

@lorgan3 does this look OK?

**Comment by TazeTSchnitzel** [comment]
This would change GB to use WASD instead of arrow keys. -1

**Comment by arctic5** [comment]
>This would change GB to use WASD instead of arrow keys. :-1:

**Comment by arctic5** [comment]
>This would change GB to use WASD instead of arrow keys. :-1:

no shit, that was kinda sorta the intended effect so you don't need to jump from arrow keys to across the keyboard when you want to test a map, and then jump back when you find an error

>Are you sure this can never cause conflicts with existing controls in GB? I must confess I know next to nothing about it ;)

pretty sure the arrow to pan across the map are the only controls in gb that are keybinds, everything else is using the mouse to click buttons

**Comment by Medo42** [comment]
@lorgan3 I'd still like to get your input on whether this is a good idea.

**Comment by lorgan3** [comment]
The original garrison builder worked with the arrow keys, but I guess it doesn't hurt to use wasd

**Comment by TazeTSchnitzel** [comment]
Maybe we could have both "main arrows" and "secondary arrows", and allow both in-game and in GB? So you could have both WASD and Up/Left/Down/Right by default.

**Comment by Medo42** [comment]
The only reason I see for not using only the configured controls in GB is that people are used to having the arrow controls for that. Maybe we could keep the arrow controls working but also accept the configured controls?

**Comment by Medo42** [comment]
Just to clarify, the difference to ajf's suggestion above is that the "secondary" controls would not be configurable and would only be accepted in GB. I think ajf's variation would be a good solution as well.

**Comment by arctic5** [comment]
o well i guess we arent having it

**Comment by TazeTSchnitzel** [comment]
I went and implemented alternate controls: https://github.com/Medo42/Gang-Garrison-2/pull/278

**Comment by arctic5** [comment]
huh i never noticed this whoops, i guess i'll close this one then

**Pull request closed without merging**
