### PR TITLE
Revert death sound

### PR DESCRIPTION
**Pull request by arctic5**

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
no

**Comment by Medo42** [comment]
@TazeTSchnitzel https://github.com/Medo42/Gang-Garrison-2/pull/224#issuecomment-52410873

**Comment by TazeTSchnitzel** [comment]
nooooo

**Comment by wareya** [comment]
rekt

**Comment by arctic5** [comment]
mfw ajf

**Pull request merged**
