### PR TITLE
Fix audio not playing correctly on Windows 10

### PR DESCRIPTION
**Pull request by PrOF-kk**
As seen [here](http://www.ganggarrison.com/forums/index.php?topic=13630.msg1289861#msg1289861). Confirmed to work on my Win 10 pc, it doesn't have 8's issues

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
Are you sure? Have you been in intense gameplay with lots of sound effects at once? Especially as say, Pyro.

**Comment by PrOF-kk** [comment]
Yes, tested today with at least 2 pyros, destroying sentries while riflemen shoot. (Casually on [EU] Parisian Paradise.
I'll be honest though, I hate it. That many sounds playing together sound awful. So we either don't push this (but then why have it enabled on Win 7 users?) or my next commit will add an hidden setting to force Win 8 mode (something like read from gg2.ini if forceWAudio == true)

**Comment by PrOF-kk** [comment]
-Added a hidden setting (forceAudioFix) for W10 or W7 users that don't like the fix
**Ready to merge** (has conflicts)

BTW My next pl will probably reorganise game_init so settings are read in order (improves code readability) but I'm out of branches for now... Image

**Comment by PrOF-kk** [comment]
> Can you cherry-pick this commit onto the current release and then post a build on the forum so that some more people can check it out?

I mean I can modify the current gmk and create an executable in about 5 minutes, but I just started using Git, until now I used GitHub Desktop (see my problems in getting even with master and why my fork is out of date) :drool:

> I'm not 100% sure the current master is still "compatible enough"

Testing on the forums/beta branch will surely tell us

**Comment by Medo42** [comment]
The general idea is: First, checkout the commit you want to start working from (make sure your working directory is clean first or it may complain):

    git checkout V2.6.8

Now you're on that commit (more precisely, the HEAD of your repository is not pointing at that commit and your working tree has been updated accordingly). However, you're not on a branch (git will warn you that you are in "detached HEAD state"). This always happens when you checkout a tag or a commit directly and not a branch. So let's make a new branch right where we are:

    git branch test-sound-changes

Now the branch exists on the commit that we are on, but we're still not on the branch (meaning, if you were to commit now the branch would keep pointing to the old commit, not the new one). Let's fix that by checking out the branch we just created:

    git checkout test-sound-changes

That didn't change the commit that we're on, but now we are also on the branch and any new commit we make will also be on that branch (i.e. committing will move the branch to the new commit).

Now we can cherry-pick what we want:

    git cherry-pick 847d289faeee01c34ec3aababe55d4550625df5f
    git cherry-pick a33d928923b12de36df6bc7af9216477c8ad59c4

Aand that's it, now you can run gmksplitter to get your gmk :)

The first part of this can be simplified, but I wanted to show how to do it with the "basic" steps first. So the first three commands can be done all at once:

    git checkout -b test-sound-changes V2.6.8

This will make a new branch at the same commit that V2.6.8 points to and then check out that branch.

Hope that helps :)

**Comment by PrOF-kk** [comment]
I actually learned a lot, but it gives me a bad object error after following exactly what you've done

**Comment by PrOF-kk** [comment]
Hey! I managed to update my fork with the latest Medo/master changes via Git and it's awesome!
BTW will post the manually modified and compiled exe on the forums sometime today

**Comment by Medo42** [comment]
Cool. Where did the "bad object error" happen though, in git or gmksplitter? Screenshot might be helpful. Also, you could join the `#gg2_dev` IRC channel. It's super quiet these days and contains almost the same people as `#gg2`, but if we're both kind of active on gg2 now we could use that for discussions.

**Pull request merged**
