### PR TITLE
"you can never have too many options with tabs"

### PR DESCRIPTION
**Pull request by arctic5**
~~Added option for corpse tracking~~
~~Fix Corpse Tracking breaking plugins that use keyboard_string (basically chat)~~
Added option for scoreboard fading

### CODE REVIEW

**Comment by Medo42** [comment]
Options do more than just take up visual space, they also add more moving parts to a program and hence more potential for undiscovered bugs, since you can't test all combinations of options. And even if it was just visual space, I don't think users like to see too many fiddly options they don't care about.

For the scoreboard fading it's really just a menu thing, but why do we need to make corpse tracking optional?

**Comment by TazeTSchnitzel** [comment]
Yes, is there really a good reason why we should allow *disabling* it?

**Comment by TazeTSchnitzel** [comment]
Or, if it is optional, does it have to go in a menu? Is it that common?

**Comment by arctic5** [comment]
>but why do we need to make corpse tracking optional?

**Comment by arctic5** [comment]
>but why do we need to make corpse tracking optional?

because i dont like it enabled and would like to disable it and I'm sure I'm not the only one that feels this way?

>Or, if it is optional, does it have to go in a menu? Is it that common?

yes, ini options are a pain to open a text editor find the option and change it + you cant change it on the fly so if i suddenly decide that having my scoreboard pop up in my face is shit i dont have to leave the game, open the file, find it, change it, reboot the game and hope someone didnt occupy the last slot on the server i just used. otherwise im stuck with a scoreboard popping up in my face  until i reboot the game and even remember it.

>I don't think users like to see too many fiddly options they don't care about.

people are fine with dsm :)

**Comment by Medo42** [comment]
We should get the keyboard clear fix from here or from the separate commit linked with the issue. Still needs checking though.

Scoreboard fade option: Maybe we should just not fade it at all, other games don't, either. If we keep it an option purely for performance reasons for wine users, maybe it should be part of a broader setting (no overlay fading)? In any case is probably better to expose it in the menu as we don't have excessive clutter.

Corpse taking option seems to be a misnomer since it appears to disable automatic player tracking entirely. I'm still unconvinced that there needs to be an option to disable it, but on the other hand I was probably overreacting with the option-aversion earlier. It shouldn't affect maintainability since it's very small and straightforward.

**Comment by arctic5** [comment]
the keyboard clear fix in this one doesn't work

**Comment by MrRatermat** [comment]
> because i dont like it enabled and would like to disable it and I'm sure I'm not the only one that feels this way?

I agree with this.

**Comment by arctic5** [comment]
>Corpse taking option seems to be a misnomer since it appears to disable automatic player tracking entirely.

Alternately, disabling it could spawn the spectator object where the player was last alive so the camera doesn't jump to a random location when the player dies

**Comment by arctic5** [comment]
It seems the general opinion is against an option for corpse tracking so I removed it, Scoreboard fading seems like a thing that should be included as an option, since we have plenty of room to add it into hud options anyways

**Comment by Medo42** [comment]
Just... why did you have to put the code between the tablinks?

**Comment by TazeTSchnitzel** [comment]
Indeed. What the hell?

**Comment by arctic5** [comment]
lol what the fuck i didnt notice that

**Pull request merged**
