### PR TITLE
Change parallax "knob" to sliders & fix 0 depth

### PR DESCRIPTION
**Pull request by wareya**

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
while you're at it can you fix vertical parallax

I still don't understand why it doesn't match PyGG2

**Comment by Medo42** [comment]
Garrison Builder -> Free mode -> click on "Offsets" in the layer controls (bottom right) -> click the up button in the layer controls.

ERROR in
action number 1
of Draw Event
for object Builder:

Error in code at line 178:
draw_text(xOffset+13, yOffset+13-43, "X: " + string(ParallaxController.background_xfactor[layerIndex]));
^
at position 81: Unknown variable background_xfactor or array index out of bounds

Apart from that, what's the idea behind using the name "offset" for those values? Is that an established convention? It feels somewhat wrong to me since I consider an offset to be a fixed shift, while this is about shift drift. IIRC I called this "parallax speed" in JGang.

**Comment by wareya** [comment]
It's the depth.

Will look at the error.

**Comment by wareya** [comment]
Fixed.

**Comment by Medo42** [comment]
If 0 means"don't move", isn't it technically more like closeness? ;)

Alexander Nadeau <notifications@github.com> schrieb am So., 05.04.2015,
20:47:

**Comment by wareya** [comment]
0 is an exception case because otherwise you wouldn't be able to input "infinite distance", which is more meaningful than "infinite closeness".

**Comment by TazeTSchnitzel** [comment]
does GM not follow IEEE754

**Comment by wareya** [comment]
Doesn't even matter, infinite closeness is a meaningless concept

**Comment by TazeTSchnitzel** [comment]
no like

I think close: 0 makes less sense than distance: INF

so you should do distance: INF

**Comment by wareya** [comment]
you can't *input* INF
right now high numbers mean less movement and it's literally a distance->parallax calculation and all is well except that you can't make a parallax calculation for infinite distance, so that's what zero does. It's perfect because 0 means nothing otherwise as well.

**Comment by TazeTSchnitzel** [comment]
make INF a possible input

**Comment by wareya** [comment]
No.

**Comment by Medo42** [comment]
GM really, really doesn't like Inf. I don't think you can have it in a variable, since any calculation that would produce it as a result will cause an FPU exception that GM treats as error.

**Comment by TazeTSchnitzel** [comment]
Fun!

**Comment by arctic5** [comment]
It's possible for the cursor to glitch and not revert when you release the mouse button

**Comment by wareya** [comment]
What? I know that it can go offscreen and un-lock if you swing really hard and the cursor goes off the screen before it's reset, but that's not fixable

**Comment by arctic5** [comment]
just run a check every step to make sure the cursor being drawn is the correct cursor

**Comment by Medo42** [comment]
Messing around with this, it looks like you can't change the background depth (fair enough), but the controls look like you can. When you try to change the depth on either the background or on a cleared layer, the cursor changes and then doesn't change back when you release the mouse button.

IMO the "Depth" button shouldn't even be shown when the depth can't be changed anyway, and the depth controls should be reset when the layer is changed.

It's also unfortunate that a control which works like this and doesn't really capture the mouse in the window is so close to the window's edge. Yes, it can be moved, but "bad by default" is no good. Saying "It's not fixable" is utterly silly. It's like building a fireplace out of wood, and when it catches fire you say "Wood is flammable, not our fault, can't fix it."

**Comment by arctic5** [comment]
alternatively have actual sliders

**Comment by wareya** [comment]
I'll fix the colors, but the display behavior must be kept as-is to reflect the way saving parallax changes behaves, which is better than changing that and making it less useful just in order to reflect a random display behavior.

I'll look at the unlocking stuff.

**Comment by wareya** [comment]
Responded to worries.

**Comment by Medo42** [comment]
Still buggy.

Create new free mode map -> switch layer to something that theoretically supports depth -> click "Depth" -> try to change the x or y depth

Expected: The control refuses to do anything
Actual: The control captures the cursor and never lets go

**Comment by wareya** [comment]
Will investigate tonight or tomorrow

**Pull request closed without merging**
