### PR TITLE
replace wareyas cursors with new ones that better indicate their purpose

### PR DESCRIPTION
**Pull request by arctic5**
I went for an aseprite look because its pixelly and seemed to fit the style. 

http://puu.sh/h3l6D/b731dbfb3d.png

Also merge wareyas pr first

mfw i cant spell cursor

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
pretty! :3

**Comment by Medo42** [comment]
I prefer these to wareya's old or new.
@wareya, care to pull them into your branch?

**Comment by TazeTSchnitzel** [comment]
We could just use Windows's own cursors for this purpose?

**Comment by TazeTSchnitzel** [comment]
Not sure if that's possible from GM though.

**Comment by Medo42** [comment]
It is, using `window_set_cursor`.

**Comment by TazeTSchnitzel** [comment]
Maybe we should be using Windows cursors in the editor generally (no GG2 cursor). The default Windows pointer is much better suited to precise manipulation than a crosshair. The crosshair is great in-game, but it's not what you need for the map editor.

**Comment by wareya** [comment]
I'll add arctic's later

**Comment by arctic5** [comment]
o well i guess we arent having it

**Comment by TazeTSchnitzel** [comment]
OK, I made a pull request to use the Windows cursor within Garrison Builder: https://github.com/Medo42/Gang-Garrison-2/pull/279

**Comment by Medo42** [comment]
Closing because it depends on / improves wareya's slider changes, and wareya closed that PR a year ago.

**Pull request closed without merging**
